config/routes.rb
require 'sidekiq/web'
# root 'pages#home'
# skip_before_action :authenticate_user!, :only => [:index]

Rails.application.routes.draw do
#   devise_for :users
#   devise_for :users, controllers: { ... , sessions: "sessions", ... }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  get '/ates/export', to: 'ates#export'
  resources :ates
  resources :ates_imports, only: [:new, :create]

  resources :anonces

  get '/objectivity_ate_marks/export', to: 'objectivity_ate_marks#export'
  resources :objectivity_ate_marks
  resources :objectivity_ate_marks_imports, only: [:new, :create]

  get '/objectivity_ou_marks/export', to: 'objectivity_ou_marks#export'
  resources :objectivity_ou_marks
  resources :objectivity_ou_marks_imports, only: [:new, :create]


  get '/monitoring_objectivity_ous/export', to: 'monitoring_objectivity_ous#export'
  resources :monitoring_objectivity_ous
  resources :monitoring_objectivity_ous_imports, only: [:new, :create]

  get '/monitoring_objectivity_ates/export', to: 'monitoring_objectivity_ates#export'
  resources :monitoring_objectivity_ates
  resources :monitoring_objectivity_ates_imports, only: [:new, :create]

  get '/mouos/export', to: 'mouos#export'
  resources :mouos
  resources :mouos_imports, only: [:new, :create]

  get '/ous/export', to: 'ous#export'
  resources :ous
  resources :ous_imports, only: [:new, :create]

  get '/results/export', to: 'results#export'
  resources :results
  resources :results_imports, only: [:new, :create, :index]

  get '/answers/export', to: 'answers#export'
  resources :answers
  resources :answers_imports, only: [:new, :create]

  get '/subjects/export', to: 'subjects#export'
  resources :subjects
  resources :subjects_imports, only: [:new, :create]

  get '/process_conditions/export', to: 'process_conditions#export'
  resources :process_conditions
  resources :process_conditions_imports, only: [:new, :create]

  get '/test_types/export', to: 'test_types#export'
  resources :test_types
  resources :test_types_imports, only: [:new, :create]

  get '/task_specifications/export', to: 'task_specifications#export'
  resources :task_specifications
  resources :task_specifications_imports, only: [:new, :create]

  get '/teacher_statements/export', to: 'teacher_statements#export'
  resources :teacher_statements
  resources :teacher_statements_imports, only: [:new, :create]

  get '/task_recomendations/export', to: 'task_recomendations#export'
  resources :task_recomendations
  resources :task_recomendations_imports, only: [:new, :create]

  get '/user_test_types/export', to: 'user_test_types#export'
  resources :user_test_types
  resources :user_test_types_imports, only: [:new, :create]

  get '/appeals/export', to: 'appeals#export'
  resources :appeals
  resources :appeals_imports, only: [:new, :create]

  get '/appeal_conditions/export', to: 'appeal_conditions#export'
  resources :appeal_conditions
  resources :appeal_conditions_imports, only: [:new, :create]

  get '/appeal_types/export', to: 'appeal_types#export'
  resources :appeal_types
  resources :appeal_types_imports, only: [:new, :create]

  get '/appeal_stations/export', to: 'appeal_stations#export'
  resources :appeal_stations
  resources :appeal_stations_imports, only: [:new, :create]

  get '/my_apellations', to: 'home#my_apellations'
  get '/apellations', to: 'home#apellations'
  get '/privacy', to: 'home#privacy'
  get '/help', to: 'home#help'
  get '/terms', to: 'home#terms'
  get '/show_result/:id', to: 'home#show_result'
  get '/show_recomendations/:id', to: 'home#show_recomendations'
  get '/show_appeals/:id', to: 'home#show_appeals'
  get '/show_blank/:id', to: 'home#show_blank'
  get '/show_results_list', to: 'home#show_results_list'
  get '/monitoring_objectivity_ates_imports', to: 'monitoring_objectivity_ates_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  resources :show_blanks, only: [:index, :show]
  resources :youtube, only: :show
  resources :tables, only: [:show, :create, :update]

  # Для регистрации
  get '/citizenships/export', to: 'citizenships#export'
  get '/citizenships/modaledit/:id', to: 'citizenships#modaledit'
  resources :citizenships
  resources :citizenships_imports, only: [:new, :create, :index]

  get '/document_types/export', to: 'document_types#export'
  get '/document_types/modaledit/:id', to: 'document_types#modaledit'
  resources :document_types
  resources :document_types_imports, only: [:new, :create, :index]

  get '/regions/export', to: 'regions#export'
  get '/regions/modaledit/:id', to: 'regions#modaledit'
  resources :regions
  resources :regions_imports, only: [:new, :create, :index]

  get '/ege_participant_categories/export', to: 'ege_participant_categories#export'
  get '/ege_participant_categories/modaledit/:id', to: 'ege_participant_categories#modaledit'
  resources :ege_participant_categories
  resources :ege_participant_categories_imports, only: [:new, :create, :index]

  get '/exams/export', to: 'exams#export'
  get '/exams/modaledit/:id', to: 'exams#modaledit'
  resources :exams
  resources :exams_imports, only: [:new, :create, :index]

  get '/exam_waves/export', to: 'exam_waves#export'
  get '/exam_waves/modaledit/:id', to: 'exam_waves#modaledit'
  resources :exam_waves
  resources :exam_waves_imports, only: [:new, :create, :index]

  get '/registration_places/export', to: 'registration_places#export'
  get '/registration_places/modaledit/:id', to: 'registration_places#modaledit'
  resources :registration_places
  resources :registration_places_imports, only: [:new, :create, :index]

  get '/ege_statements/export', to: 'ege_statements#export'
  get '/ege_statements/modaledit/:id', to: 'ege_statements#modaledit'
  resources :ege_statements
  resources :ege_statements_imports, only: [:new, :create, :index]
  get '/ege_statements/get_registration_places', to: "ege_statements#get_registration_places"
  get '/get_registration_places', to: "ege_statements#get_registration_places"

  get '/answer_types/export', to: 'answer_types#export'
  get '/answer_types/modaledit/:id', to: 'answer_type#modaledit'
  resources :answer_types
  resources :answer_types_imports, only: [:new, :create, :index]

  get '/question_types/export', to: 'question_types#export'
  get '/question_types/modaledit/:id', to: 'question_type#modaledit'
  resources :question_types
  resources :question_types_imports, only: [:new, :create, :index]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  # root :to => redirect("/users/sign_in")

  root :to => 'home#index'

  #
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mouo.rb
class Mouo < ApplicationRecord

  include PgSearch::Model

  belongs_to :ate
  validates :name, presence: true
  validates :code, presence: true
  validates :ate_id, presence: true
  validates :contact_fio, presence: true
  validates :contact_phone, presence: true
  has_many :ous
  # has_many :monitoring_objectivity_ates
  has_many :appeal_stations

  def self.search(search)
    if search
      where('name || cast(code as varchar(5)) LIKE ?', "%#{search}%")
    end
  end

  def short_name
    ate = Ate.where(:code => self.code).first
    if !ate.nil?
      return "ОМСУ " + ate.name
    else
      if self.code == 95
        return 'ГОУ Свердловской области'
      end
      if self.code == 97
        return 'Негосударственные ОУ'
      end
      return self.name
    end
  end

  def short_name_code
    ate = Ate.where(:code => self.code).first
    if !ate.nil?
      return ("00" + self.code.to_s)[-2..-1] + " ОМСУ " + ate.name
    else
      if self.code == 95
        return '95 ГОУ Свердловской области'
      end
      if self.code == 97
        return '97 Негосударственные ОУ'
      end
      return ("00" + self.code.to_s)[-2..-1] + " " + self.name
    end
  end


  self.per_page = 20

  # set per_page globally
  WillPaginate.per_page = 20

end

app/controllers/mouos_controller.rb
class MouosController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!

  def index
    @mouos = Mouo.accessible_by(current_ability).paginate(page: params[:page]).order('code ASC')
    if current_user.admin?
      if !params[:search].nil?
        @mouos = Mouo.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('code ASC')
      end
    else
      if !params[:search].nil?
        @mouos = Mouo.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('code ASC')
      end
    end
  end

  def export
    @mouos = Mouo.accessible_by(current_ability)
    render xlsx: 'mouos_list_' + DateTime.now.getlocal.to_s.gsub(' ', '-').gsub(':', '.'), template: '/mouos/export.xlsx.axlsx'
  end

  def new
    @mouo = Mouo.new
    @ates = Ate.accessible_by(current_ability)
    if !@mouo.nil?
      render :edit
    else
      flash[:success] = t("mouos.errors.cant_create_new")
      redirect_to :action => 'index'
    end
  end

  def show
    @mouo = Mouo.accessible_by(current_ability).find(params[:id])
  end

  def create
    @ates = Ate.accessible_by(current_ability)
    @mouo = Mouo.new(mouo_params)
    if @mouo.save
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @ates = Ate.accessible_by(current_ability)
    @mouo = Mouo.accessible_by(current_ability).find(params[:id])
  end

  def delete
    Mouo.accessible_by(current_ability).find(params[:id]).destroy
    return
  end

  def destroy
    @mouo = Mouo.accessible_by(current_ability).find(params[:id])
    @mouo.destroy
    respond_to do |format|
      format.html { redirect_to mouos_url, notice: t("mouos.notice.destroyed") }
      format.json { head :no_content }
    end
    # redirect :action => 'index'
  end

  def update
    @mouo = Mouo.accessible_by(current_ability).find params[:id]
    # respond_to do |format|
    if @mouo.update mouo_params
      flash[:success] = t("mouos.notice.updated")
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end


  def mouo_params
    params.require(:mouo).permit(:code, :name, :ate_id, :contact_fio, :contact_phone)
  end


end

app/views/mouos/_edit.html.haml
%h4= t("mouos.actions.edit")
= form_for @mouo do |f|
  .form-group
    %table
      %tr
        %td= t("mouos.code")
        %td= f.number_field :code, autofocus: false, placeholder: t("mouos.code"), class: 'form-control'
      %tr
        %td= t("mouos.full_name")
        %td= f.text_field :name, autofocus: false, placeholder: t("mouos.name"), class: 'form-control'
      %tr
        %td= t("mouos.ate_full_name")
        %td= f.collection_select :ate_id, @ates, :id, :name, prompt: true, placeholder: t('mouo.choose_ate')
      %tr
        %td= t("mouos.contact_fio")
        %td= f.text_field :contact_fio, autofocus: false, placeholder: t("mouos.contact_fio"), class: 'form-control'
      %tr
        %td= t("mouos.contact_phone")
        %td= f.text_field :contact_phone, autofocus: false, placeholder: '+7-xxx-xxx-xxxx', class: 'form-control'
      %tr
        %td{:colspan=>2}
          .form-actions
            = f.submit @mouo.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-placement" => "bottom"
            = link_to t("buttons.cancel"), {:action => 'index'}

app/views/mouos/_list.html.haml
-if @mouos.count > 20
  .apple_pagination
    = will_paginate @mouos

%table.table.table-striped
  %thead
    -if current_user.admin?
      %th= t("mouos.id")
    %th= t("mouos.code")
    %th= t("mouos.full_name")
    %th= t("mouos.ate_name")
    %th= t("mouos.contact_fio")
    %th= t("mouos.contact_phone")
    -if current_user.admin?
      %th= t("mouos.created_at")
      %th= t("mouos.updated_at")
    -if current_user.admin? or current_user.mouo_role?
      %th= t("mouos.actions.title")
  %tbody
    - @mouos.each do |row|
      %tr
        -if current_user.admin?
          %td= row.id.to_s
        %td= row.code.to_s
        %td= row.name.to_s
        %td= row.ate.name.to_s
        %td= row.contact_fio.to_s
        %td= row.contact_phone.to_s
        -if current_user.admin?
          %td= row.created_at.to_s
          %td= row.updated_at.to_s
        -if current_user.admin? or current_user.mouo_role?
          %td
            - if can? :edit, Mouo
              = link_to edit_mouo_path(row) do
                = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
            - if can? :delete, Mouo
              = link_to mouo_path(row), :method => :delete,  data: { confirm: t('delete_confirm')} do
                = bootstrap_icon "trash", width: 15, height: 15, fill: "red"

-if @mouos.count > 20
  .apple_pagination
    = will_paginate @mouos

app/views/mouos/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/mouos/index.html.haml
.row
  .span9
    %h3.pull-left= t("mouos.list.title")
    -# = render_notice
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            = form_tag mouos_path, :method => 'get', :id => "mouos_search" do
              %p
                = text_field_tag :search, params[:search]
                = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
                  = bootstrap_icon "search", width: 25, height: 25, fill: "blue"
          %td
            - if can? :create, Mouo
              = link_to new_mouo_path do
                = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
            - if can? :export, Mouo
              = link_to mouos_export_path do
                = bootstrap_icon "download", width: 15, height: 15, fill: "blue"
            - if can? :create, Ate
              = link_to new_mouos_import_path do
                = bootstrap_icon "upload", width: 15, height: 15, fill: "blue"


    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t(".title")}

app/views/mouos/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/mouos/show.html.haml
-# -@id=params[:id]
%h1 Наименование проекта
%h2=@mouo.name.to_s
%table
  %tr
    %td=t("mouos.code")
    %td=@mouo.code.to_s
  %tr
    %td=t("mouos.full_name")
    %td=@mouo.name
%div
  = link_to "Вернуться", mouos_path, :class => "btn btn-primary btn-mini"