config/routes.rb
require 'sidekiq/web'
# root 'pages#home'
# skip_before_action :authenticate_user!, :only => [:index]

Rails.application.routes.draw do
#   devise_for :users
#   devise_for :users, controllers: { ... , sessions: "sessions", ... }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # mount RailsAdmin::Engine => '/rails_admin', :as => 'rails_admin'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: "users#index"
  end

  get '/ates/export', to: 'ates#export'
  resources :ates
  resources :ates_imports, only: [:new, :create]

  resources :anonces

  get '/objectivity_ate_marks/export', to: 'objectivity_ate_marks#export'
  resources :objectivity_ate_marks
  resources :objectivity_ate_marks_imports, only: [:new, :create]

  get '/objectivity_ou_marks/export', to: 'objectivity_ou_marks#export'
  resources :objectivity_ou_marks
  resources :objectivity_ou_marks_imports, only: [:new, :create]


  get '/monitoring_objectivity_ous/export', to: 'monitoring_objectivity_ous#export'
  resources :monitoring_objectivity_ous
  resources :monitoring_objectivity_ous_imports, only: [:new, :create]

  get '/monitoring_objectivity_ates/export', to: 'monitoring_objectivity_ates#export'
  resources :monitoring_objectivity_ates
  resources :monitoring_objectivity_ates_imports, only: [:new, :create]

  get '/mouos/export', to: 'mouos#export'
  resources :mouos
  resources :mouos_imports, only: [:new, :create]

  get '/ous/export', to: 'ous#export'
  resources :ous
  resources :ous_imports, only: [:new, :create]

  get '/results/export', to: 'results#export'
  resources :results
  resources :results_imports, only: [:new, :create, :index]

  get '/answers/export', to: 'answers#export'
  resources :answers
  resources :answers_imports, only: [:new, :create]

  get '/subjects/export', to: 'subjects#export'
  resources :subjects
  resources :subjects_imports, only: [:new, :create]

  get '/process_conditions/export', to: 'process_conditions#export'
  resources :process_conditions
  resources :process_conditions_imports, only: [:new, :create]

  get '/test_types/export', to: 'test_types#export'
  resources :test_types
  resources :test_types_imports, only: [:new, :create]

  get '/task_specifications/export', to: 'task_specifications#export'
  resources :task_specifications
  resources :task_specifications_imports, only: [:new, :create]

  get '/teacher_statements/export', to: 'teacher_statements#export'
  resources :teacher_statements
  resources :teacher_statements_imports, only: [:new, :create]

  get '/task_recomendations/export', to: 'task_recomendations#export'
  resources :task_recomendations
  resources :task_recomendations_imports, only: [:new, :create]

  get '/user_test_types/export', to: 'user_test_types#export'
  resources :user_test_types
  resources :user_test_types_imports, only: [:new, :create]

  get '/appeals/export', to: 'appeals#export'
  resources :appeals
  resources :appeals_imports, only: [:new, :create]

  get '/appeal_conditions/export', to: 'appeal_conditions#export'
  resources :appeal_conditions
  resources :appeal_conditions_imports, only: [:new, :create]

  get '/appeal_types/export', to: 'appeal_types#export'
  resources :appeal_types
  resources :appeal_types_imports, only: [:new, :create]

  get '/appeal_stations/export', to: 'appeal_stations#export'
  resources :appeal_stations
  resources :appeal_stations_imports, only: [:new, :create]

  get '/my_apellations', to: 'home#my_apellations'
  get '/apellations', to: 'home#apellations'
  get '/privacy', to: 'home#privacy'
  get '/help', to: 'home#help'
  get '/terms', to: 'home#terms'
  get '/show_result/:id', to: 'home#show_result'
  get '/show_recomendations/:id', to: 'home#show_recomendations'
  get '/show_appeals/:id', to: 'home#show_appeals'
  get '/show_blank/:id', to: 'home#show_blank'
  get '/show_results_list', to: 'home#show_results_list'
  get '/monitoring_objectivity_ates_imports', to: 'monitoring_objectivity_ates_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'
  get '/monitoring_objectivity_ous_imports', to: 'monitoring_objectivity_ous_imports#new'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]

  resources :show_blanks, only: [:index, :show]
  resources :youtube, only: :show
  resources :tables, only: [:show, :create, :update]

  # Для регистрации
  get '/citizenships/export', to: 'citizenships#export'
  get '/citizenships/modaledit/:id', to: 'citizenships#modaledit'
  resources :citizenships
  resources :citizenships_imports, only: [:new, :create, :index]

  get '/document_types/export', to: 'document_types#export'
  get '/document_types/modaledit/:id', to: 'document_types#modaledit'
  resources :document_types
  resources :document_types_imports, only: [:new, :create, :index]

  get '/regions/export', to: 'regions#export'
  get '/regions/modaledit/:id', to: 'regions#modaledit'
  resources :regions
  resources :regions_imports, only: [:new, :create, :index]

  get '/ege_participant_categories/export', to: 'ege_participant_categories#export'
  get '/ege_participant_categories/modaledit/:id', to: 'ege_participant_categories#modaledit'
  resources :ege_participant_categories
  resources :ege_participant_categories_imports, only: [:new, :create, :index]

  get '/exams/export', to: 'exams#export'
  get '/exams/modaledit/:id', to: 'exams#modaledit'
  resources :exams
  resources :exams_imports, only: [:new, :create, :index]

  get '/exam_waves/export', to: 'exam_waves#export'
  get '/exam_waves/modaledit/:id', to: 'exam_waves#modaledit'
  resources :exam_waves
  resources :exam_waves_imports, only: [:new, :create, :index]

  get '/registration_places/export', to: 'registration_places#export'
  get '/registration_places/modaledit/:id', to: 'registration_places#modaledit'
  resources :registration_places
  resources :registration_places_imports, only: [:new, :create, :index]

  get '/ege_statements/export', to: 'ege_statements#export'
  get '/ege_statements/modaledit/:id', to: 'ege_statements#modaledit'
  resources :ege_statements
  resources :ege_statements_imports, only: [:new, :create, :index]
  get '/ege_statements/get_registration_places', to: "ege_statements#get_registration_places"
  get '/get_registration_places', to: "ege_statements#get_registration_places"

  get '/answer_types/export', to: 'answer_types#export'
  get '/answer_types/modaledit/:id', to: 'answer_type#modaledit'
  resources :answer_types
  resources :answer_types_imports, only: [:new, :create, :index]

  get '/question_types/export', to: 'question_types#export'
  get '/question_types/modaledit/:id', to: 'question_type#modaledit'
  resources :question_types
  resources :question_types_imports, only: [:new, :create, :index]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  # root :to => redirect("/users/sign_in")

  root :to => 'home#index'

  #
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task_specification.rb
class TaskSpecification < ActiveRecord::Base

  belongs_to :subject
  belongs_to :test_type
  has_rich_text :competention_type
  has_rich_text :competention_name
  has_rich_text :zun_name

  def to_s
    return name
  end

  def self.search(search)
    if search
      where('cast(task_number as varchar(5)) LIKE ?', "%#{search}%")
    end
  end

  ##################################################################################################
  ### Includes and Extensions ######################################################################


  ##################################################################################################
  ### Associations #################################################################################


  ##################################################################################################
  ### Callbacks ####################################################################################


  ##################################################################################################
  ### Validations ##################################################################################



  ##################################################################################################
  ### Scopes #######################################################################################


  ##################################################################################################
  ### Other ########################################################################################


  ##################################################################################################
  ### Class Methods ################################################################################


  ##################################################################################################
  ### Instance Methods #############################################################################


  #########
  protected
  #########


  #######
  private
  #######

  self.per_page = 10

  # set per_page globally
  WillPaginate.per_page = 10

end

app/controllers/task_specifications_controller.rb
class TaskSpecificationsController < ApplicationController
  load_and_authorize_resource :instance_name => :item
  before_action :authenticate_user!

  def index
    @test_types=TestType.all
    @subjects=Subject.all
    @task_specifications = TaskSpecification.accessible_by(current_ability).paginate(page: params[:page]).order('id ASC')
    if !params[:search].nil?
      @task_specifications = TaskSpecification.accessible_by(current_ability).search(params[:search]).paginate(page: params[:page]).order('id ASC')
    end
  end

  def export
    @task_specifications = TaskSpecification.accessible_by(current_ability).order('id ASC')
    render xlsx: 'task_specifications_list_' + DateTime.now.getlocal.to_s.gsub(' ', '-').gsub(':', '.'), template: '/task_specification/export.xlsx.axlsx'
  end


  def new
    @test_types=TestType.all
    @subjects=Subject.all
    @task_specification = TaskSpecification.new
  end

  def show
    @task_specification = TaskSpecification.find(params[:id])
  end

  def create
    @test_types=TestType.all
    @subjects=Subject.all
    @task_specification = TaskSpecification.new(task_specifications_params)
    if @task_specification.save
      redirect_to :action => 'index'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render :action => 'new'
    end
  end

  def edit
    @test_types=TestType.all
    @subjects=Subject.all
    @task_specification = TaskSpecification.find(params[:id])
  end

  def delete
    TaskSpecification.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  def destroy
    @task_specification = TaskSpecification.find(params[:id])
    @task_specification.destroy
    respond_to do |format|
      format.html { redirect_to task_specifications_url, notice: t("task_specification.notice.destroyed") }
      format.json { head :no_content }
    end
  end


  def update
    @task_specification = TaskSpecification.find params[:id]
    # respond_to do |format|
    if @task_specification.update task_specifications_params
      flash[:success] = t("task_specification.notice.updated")
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def task_specifications_params
    params.require(:task_specification).permit(:test_type_id, :subject_id, :task_number, :competention_type, :competention_name, :zun_name, :max_ball)
  end

end

app/views/task_specifications/_edit.html.haml
%h4= t("task_specifications.edit.title")

= form_for @task_specification do |f|
  .form-group
    %table
      %tr
        %td= t("task_specifications.choose_test_type")
        %td= f.collection_select :test_type_id, @test_types, :id, :name, prompt: true, placeholder: t('task_specification.choose_test_type')
      %tr
        %td= t("task_specifications.choose_subject")
        %td= f.collection_select :subject_id, @subjects, :id, :subject_name, prompt: true, placeholder: t('task_specification.choose_subject')
      %tr
        %td= t("task_specifications.task_number")
        %td= f.number_field :task_number, autofocus: false, placeholder: t("task_specifications.task_number"), class: 'form-control'
      %tr
        %td= t("task_specifications.competention_type")
        %td= f.rich_text_area :competention_type, autofocus: false, placeholder: t("task_specifications.competention_type"), class: 'form-control'
      %tr
        %td= t("task_specifications.competention_name")
        %td= f.rich_text_area :competention_name, autofocus: false, placeholder: t("task_specifications.competention_name"), class:'form-control customized-min-height'
      %tr
        %td= t("task_specifications.zun_name")
        %td= f.rich_text_area :zun_name, autofocus: false, placeholder: t("task_specifications.zun_name"), class: 'form-control'
      %tr
        %td= t("task_specifications.max_ball")
        %td= f.number_field :max_ball, autofocus: false, placeholder: t("task_specifications.max_ball"), class: 'form-control'
      %tr
        %td{:colspan=>2}
          .form-actions
            = f.submit @task_specification.new_record? ? t("buttons.create") : t("buttons.save"), :class => 'btn btn-primary btn-with-tooltip',"data-original-title" => t("messages.tooltips.save"),"data-placement" => "bottom"
            = link_to t("buttons.cancel"), {:action => 'index'}

app/views/task_specifications/_list.html.haml
-if !@task_specifications.nil?
  .results-count.clear
    =t("messages.search.find_results")
    =@task_specifications.count

  -if @task_specifications.count > 10
    .apple_pagination
      = will_paginate @task_specifications

  %table.table.table-bordered
    %thead
      %th= t("task_specifications.id")
      %th= t("task_specifications.test_type")
      %th= t("task_specifications.subject")
      %th= t("task_specifications.task_number")
      %th= t("task_specifications.competention_type")
      %th= t("task_specifications.competention_name")
      %th= t("task_specifications.zun_name")
      %th= t("task_specifications.max_ball")
      %th= t("task_specifications.actions.title")
    %tbody
      - @task_specifications.each do |pr|
        %tr
          %td= pr.id.to_s
          %td= link_to pr.test_type.to_s, task_specifications_path(pr)
          %td= link_to pr.subject.to_s, task_specifications_path(pr)
          %td= link_to pr.task_number.to_s, task_specifications_path(pr)
          %td= link_to truncate(pr.competention_type.to_plain_text, :length=>20), task_specifications_path(pr)
          %td= link_to truncate(pr.competention_name.to_plain_text, :length=>60), task_specifications_path(pr)
          %td= link_to truncate(pr.zun_name.to_plain_text, :length=>60), task_specifications_path(pr)
          %td= best_in_place pr, :max_ball, :as => :input
          %td
            = link_to edit_task_specification_path(pr), :title => t("buttons.edit") do
              = bootstrap_icon "pencil", width: 15, height: 15, fill: "green"
            = link_to task_specifications_path(pr), :method => :delete, :title => t("buttons.delete") do
              = bootstrap_icon "trash", width: 15, height: 15, fill: "red"

  -if @task_specifications.count > 10
    .apple_pagination
      = will_paginate @task_specifications
-else
  %p="Не найдено"

app/views/task_specifications/edit.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/task_specifications/index.html.haml
.row
  .span9
    %h3.pull-left= t("task_specifications.list.title")
    -# = render_notice
    %span.top-panel-actions
      %table.table.borderless
        %tr
          %td
            = form_tag task_specifications_path, :method => 'get', :id => "task_specifications_search" do
              %p
                = text_field_tag :search, params[:search]
                = button_tag(type: "submit", class: "btn btn-default", :name => nil) do
                  = bootstrap_icon "search", width: 25, height: 25, fill: "blue"
          %td
            - if can? :create, TaskSpecification
              = link_to new_task_specification_path do
                = bootstrap_icon "file-plus", width: 15, height: 15, fill: "blue"
            - if can? :export, TaskSpecification
              = link_to task_specifications_export_path do
                = bootstrap_icon "download", width: 15, height: 15, fill: "blue"
            - if can? :create, TaskSpecification
              = link_to new_task_specifications_import_path do
                = bootstrap_icon "upload", width: 15, height: 15, fill: "blue"


    %span.marks-filter-target
      = render :partial => 'list', :locals => {:legend => t(".title")}

app/views/task_specifications/new.html.haml
= render :partial => 'edit', :locals => {:legend => t(".title")}

app/views/task_specifications/show.html.haml
%h1=t("task_specifications.title")
%table
  %tr
    %td= t('task_specification.test_type')
    %td= best_in_place @task_specification, :test_type_id, :as => :select
  %tr
    %td= t('task_specification.subject')
    %td= best_in_place @task_specification, :subject_id, :as => :select
  %tr
    %td= t('task_specification.task_number')
    %td= best_in_place @task_specification, :task_number, :as => :input
  %tr
    %td= t('task_specification.competention_type')
    %td= best_in_place @task_specification, :competention_type, :as => :input
  %tr
    %td= t('task_specification.competention_name')
    %td= best_in_place @task_specification, :competention_name, :as => :input
  %tr
    %td= t('task_specification.zun_name')
    %td= best_in_place @task_specification, :zun_name, :as => :input
  %tr
    %td= t('task_specification.max_ball')
    %td= best_in_place @task_specification, :max_ball, :as => :input

%div
  = link_to t("buttons.back"), task_specifications_path, :class => "btn btn-primary btn-mini"